options:
  max-warnings: 64

files:
  ignore:
    - 'node_modules/**/*'

rules:
  attribute-quotes:
    - 2
    -
      include: false

  bem-depth:
    - 2
    -
      max-depth: 1

  border-zero:
    - 1
    -
      convention: 0

  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false

  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  clean-import-paths:
    - 2

  declarations-before-nesting:
    - 2

  empty-args:
    - 2
    -
      include: true

  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false

  extends-before-declarations:
    - 2

  extends-before-mixins:
    - 2

  final-newline:
    - 2
    -
      include: true

  force-attribute-nesting:
    - 0

  force-element-nesting:
    - 0

  force-pseudo-nesting:
    - 0

  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  hex-length:
    - 2
    -
      style: short

  hex-notation:
    - 2
    -
      style: lowercase

  id-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  indentation:
    - 2
    -
      size: 2

  leading-zero:
    - 2
    -
      include: false

  max-file-line-count:
    - 2
    -
      length: 300

  max-line-length:
    - 2
    -
      length: 128

  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  mixins-before-declarations:
    - 2

  nesting-depth:
    - 1
    -
      max-depth: 4

  no-attribute-selectors:
    - 0

  no-color-hex:
    - 0

  no-color-keywords:
    - 0

  no-color-literals:
    - 0

  no-combinators:
    - 0

  no-css-comments:
    - 0

  no-debug:
    - 2

  no-disallowed-properties:
    - 2
    -
      properties:
        - float

  no-duplicate-properties:
    - 2

  no-empty-rulesets:
    - 2

  no-ids:
    - 1

  no-important:
    - 1

  no-invalid-hex:
    - 2

  no-mergeable-selectors:
    - 2

  no-misspelled-properties:
    - 2

  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true

  no-trailing-whitespace:
    - 2

  no-trailing-zero:
    - 2

  no-transition-all:
    - 2

  no-universal-selectors:
    - 1

  no-url-domains:
    - 0

  no-url-protocols:
    - 0

  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true

  no-warn:
    - 2

  one-declaration-per-line:
    - 2

  placeholder-in-extend:
    - 0

  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  property-sort-order:
    - 0

  property-units:
    - 1
    -
      global:
        - px
        - '%'
        - vh
        - vw
        - vmin
        - rem
        - vmax

  pseudo-element:
    - 2

  quotes:
    - 2
    -
      style: single

  shorthand-values:
    - 2

  single-line-per-selector:
    - 0

  space-after-bang:
    - 2
    -
      include: false

  space-after-colon:
    - 2

  space-after-comma:
    - 2

  space-around-operator:
    - 2

  space-before-bang:
    - 2

  space-before-brace:
    - 2

  space-before-colon:
    - 2
    -
      include: false

  space-between-parens:
    - 2
    -
      include: false

  trailing-semicolon:
    - 2

  url-quotes:
    - 0

  variable-for-property:
    - 0

  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  zero-unit:
    - 2
    -
      include: false
